name: Deploy index.php to williamtoons.com

on:
  push:
    branches:
      - main
    paths:
      - 'index.php'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4

      - name: Upload index.php with SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: './index.php'
          remote_path: '/httpdocs'
          sftp_only: true
